# Generated by Django 4.2.9 on 2024-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating_avg_movie_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
