# Generated by Django 4.2.9 on 2024-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_rating_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
