# Generated by Django 4.2.9 on 2024-02-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
    ]
