# Generated by Django 4.2.9 on 2024-02-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='idx',
            field=models.IntegerField(blank=True, help_text='Position IDs for ML', null=True),
        ),
    ]
